name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.21.0"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build test binaries
        run: go test -c -race ./...

      - name: Apply CAP_NET_RAW for icmpx
        run: sudo setcap cap_net_raw+ep ./icmpx.test

      - name: Apply CAP_NET_RAW for echo
        run: sudo setcap cap_net_raw+ep ./echo.test

      - name: Run icmpx tests
        run: ./icmpx.test -test.v

      - name: Run echo tests
        run: ./echo.test -test.v
